enyo.depends(
	"$lib/layout/fittable",
	"$lib/layout/slideable",
	"$lib/onyx",
	"$lib/webos-lib",
  	"../../../src/js/App.js",
  	"../../../src/js/Settings.js",
  	"../../../src/js/EnyoPatches.js"
);
